services:
  lb:
    image: tomcoolpxl/ubuntu-systemd-ssh:22.04
    hostname: lb
    ports:
      - 8222:22
      - 8404:8404
      - 8882:80
    cap_add:
      - NET_ADMIN
    volumes:
      - ./haproxy.cfg:/home/user/haproxy.cfg
      - ./install-ha.sh:/home/user/install-ha.sh
    networks:
      my-internal:
        ipv4_address: 192.168.1.4
      my-bridge:

  web1:
    image: tomcoolpxl/ubuntu-systemd-ssh:22.04
    hostname: web1
    ports:
      - 8223:22
      - 8883:80
    cap_add:
      - NET_ADMIN
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./install-web.sh:/home/user/install-web.sh
    networks:
      my-internal:
        ipv4_address: 192.168.1.5
      my-bridge:

  web2:
    image: tomcoolpxl/ubuntu-systemd-ssh:22.04
    hostname: web2
    ports:
      - 8224:22
      - 8884:80
    cap_add:
      - NET_ADMIN
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./install-web.sh:/home/user/install-web.sh
    networks:
      my-internal:
        ipv4_address: 192.168.1.6
      my-bridge:

networks:
  my-bridge:
    driver: bridge
  my-internal:
    internal: true
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.4
