Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/bionic64"
    web.vm.hostname = "web.local"
    web.vm.network "private_network", ip: "192.168.10.21", hostname: true
    web.vm.provision "shell", inline: <<-SHELL
      # install traceroute  
      sudo apt install -y traceroute
      # enable routing
      echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
      sudo sysctl -p
      # enable nat on eth0 10.0.2.0/24 network
      sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/bionic64"
    db.vm.hostname = "db.local"
    db.vm.network "private_network", ip: "192.168.10.22", hostname: true
    # copy netplan network configuration file to vm
    db.vm.provision "file", source: "./db_50-vagrant.yaml", destination: "/home/vagrant/50-vagrant.yaml"
    db.vm.provision "shell", inline: <<-SHELL
      # install traceroute  
      sudo apt install -y traceroute
      sudo apt install -y net-tools
      # set PasswordAuthentication to yes in sshd_config
      sudo sed -re 's/^(PasswordAuthentication)([[:space:]]+)no/\1\2yes/' -i.`date -I` /etc/ssh/sshd_config
      sudo systemctl restart sshd
      # remove default gateway virtualbox
      sudo ip route del 0/0
      # disable eth0 door netplan network interface config file te verwijderen
      sudo mv /etc/netplan/01-netcfg.yaml /home/vagrant/01-netcfg.yaml.bak
      # move netplan network configuration to corrent location
      sudo mv /home/vagrant/50-vagrant.yaml /etc/netplan/
      sudo chmod 644 /etc/netplan/50-vagrant.yaml
      # apply alle netwerk changes
      sudo netplan apply
    SHELL
  end
end