# -*- mode: ruby -*-
# vi: set ft=ruby :

# The "2" in Vagrant.configure configures the configuration version
Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web.local"
    web.vm.network "private_network", ip: "192.168.10.21", hostname: true
    web.vm.network "forwarded_port", guest: 80, host: 8888
    web.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    web.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.10.22 db" | sudo tee -a /etc/hosts
      sudo yum -y install ntp
      sudo yum -y install net-tools
      sudo timedatectl set-timezone Europe/Brussels
      sudo systemctl start ntpd
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db.local"
    db.vm.network "private_network", ip: "192.168.10.22", hostname: true
    # delete default gw on eth0
    db.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    db.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.10.21 web" | sudo tee -a /etc/hosts
      sudo yum -y install ntp
      sudo yum -y install net-tools
      sudo timedatectl set-timezone Europe/Brussels
      sudo systemctl start ntpd
      sudo ip route del 0/0
    SHELL
  end
end