# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Memory for the VMs (2GB)
  MEMORY = 2048

  # Number of nodes to provision -1
  SERVER_NODES = 2
  CLIENT_NODES = 0
  CPUS = 1

  GROUP = "/nfs-lab"

  # Box metadata location and box name
  BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
  BOX_NAME = "oraclelinux/8"

  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
    vb.customize ["modifyvm", :id, "--groups", GROUP] unless GROUP.nil?
  end

  config.vagrant.plugins = "vagrant-hosts"

  if Vagrant.has_plugin?("vagrant-hosts")
    config.vm.provision :hosts do |provisioner|
      provisioner.add_localhost_hostnames = false
      provisioner.sync_hosts = true
      provisioner.autoconfigure = true
    end
  end

  nextip = 0
  (0..SERVER_NODES).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.hostname = "server#{i}.psdemo.local"
      ip = 100 + i
      server.vm.network "private_network", ip: "192.168.99.#{ip}"
    end
    nextip = 100 + i
  end

  nextip = nextip + 1
  (0..CLIENT_NODES).each do |i|
    config.vm.define "client#{i}" do |client|
      client.vm.hostname = "client#{i}.psdemo.local"
      ip = nextip + i
      client.vm.network "private_network", ip: "192.168.99.#{ip}"
    end
  end

  config.vm.post_up_message = "Build complete"
end
